version: '3'
services:
  movies:
    image: siva995912345/moviesservice:latest
    ports:
      - "80:80"
    deploy:
      replicas: 3

  train:
    image: siva995912345/trainservice:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  dth:
    image: siva995912345/dthservice:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  recharge:
    image: siva995912345/rechargeservice:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
